# Generated by Django 3.0.3 on 2020-02-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20200223_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='country',
            field=models.CharField(default='Australia', max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='state',
            field=models.CharField(default='WA', max_length=50, verbose_name='State'),
        ),
    ]
