# Generated by Django 3.0.3 on 2020-02-23 03:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20200223_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, unique=True, verbose_name='Location'),
        ),
    ]
